### ISSUE TITLE
File Home

### ISSUE THREAD

**Issue by Loki127-4** [Lucas91z/proyecto#1]
Hola! como estas? intente subir lo poco que tengo del home pero no me deja. Logre hacer un repositorio en git hub, te paso el url para ver como lo podemos poner en el mismo lugar: https://github.com/Loki127-4/proyecto-libreria.git
Por otro lado, estoy intentando hacer un banner carrusel pero no me estaría saliendo, quería ver si alguno esta ducho con java scrip para hacerlo, sino sigo investigando como hacerlo con css, flex y grid. También quería ver si alguno hizo un footer, para agregarlo.
La idea miá es terminar el main el martes que me lo deje libre. Pensaba incluir en el cuerpo un par de libros destacados dentro de cajas (onda un rectángulo con el libro) con el precio debajo o una mini descripción.  
Aun falta terminar de hacerlo responsivo pero eso se hace rápido cuando se termine todo. Una parte ya esta responsiva para celular, me faltaria agregar para tablet y convertir el main en responsivo cuando lo termine y bueno, el footer.

**Comment by Lucas91z** [comment]
Cuando puedas fijate, creo que pude agregarte como collab (o al menos te envie una invitacion xd)

**Comment by Loki127-4** [comment]
Hola! Si, perdón ayer mori después de mandar los audios jajajajaja. Llego
del trabajo y me meto y veo si puedo subirlo.
Gracias 😊

**Comment by Loki127-4** [comment]
Buenas! recien intente subir el mio pero dice que el push esta deshabilitado, no se que onda. Si entras al link que te pase, tiene que estar la actualizacion

**Comment by Loki127-4** [comment]
no, seguimos igual. ya fue copio y pego xD

**Comment by Loki127-4** [comment]
ni copiar y pegar entiendo aca xD

**Comment by Loki127-4** [comment]
Ah no, si soy boluda, nunca habia aceptado la invitacion -_- solo le puse el tilde de ok lpm. Ya esta

**Comment by Lucas91z** [comment]
Ahi se subio una carpeta con imaegenes puede ser?
