### ISSUE TITLE
@media

### ISSUE THREAD

**Issue by Loki127-4** [Lucas91z/proyecto#11]
@media screen and (max-width: 700px) {
  .head_container {
    background-image: none;
    background-color: #4A09ED;
    background-image: linear-gradient(to bottom, #230063,#510459);
    width: 100%;

    box-sizing: border-box;

    display: flex;
    flex-direction: column;
    align-items: center;

    padding-top: .75rem;
    padding-bottom: .75rem;
  }
  .head_logo{
   max-width:100px;
   }  
  .menu{
      font-size: 2rem;
  }
  .menu.home :hover{
    background-color: initial;
    color: unset;
    font-size: 1.3rem;
    font-weight: 600;
    text-decoration: none;
  }
  .menu :hover{
    text-decoration: none;
  }
  .icono :hover{
    transform: unset;
  }
  .icono :active{
    background-color: #4A09ED;
  }
  * {
    box-sizing:content-box;
  }
  .libros{
    padding-left: 1.1rem;
    padding-right: 1.1rem;
  }
  .formulario{
    padding-left: 1.1rem;
    padding-right: 1.1rem;
  }
  element.style{
    text-align: center;
  }
  .mapa{
    max-width: 50px;
  }
  h2{
    text-align: center;
  }
  section{
    border:none;
  }

  .main_container{
    background: none;
  }
  .titulo{
    text-align: center;
    font-family: roboto;
    text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);
    background-color: #b09dc2;
  }
  .banner_container{
    border: #c78c19;
  }

**Comment by Lucas91z** [comment]
Agregado
